import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from 'next/head'
import Nav from "./components/Nav";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Prompt Share",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <meta name="google-site-verification" content="XZAfnsvIeyTz28w78JOXfYW9Yfn7od9xg3AhMAUYFYE" />
      </Head>
      <body className={inter.className}>
        {/* <Provider> */}
        <Nav />
        {children}
      </body>
      {/* </Provider> */}
    </html>
  );
}
